# Generated by Django 4.1.1 on 2022-09-29 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('photo', models.FilePathField(null=True, path='events_restapi/media/event_photos')),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('city', models.CharField(max_length=120)),
                ('approved', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventhost', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='eventparticipants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
