# Generated by Django 4.1.1 on 2022-09-30 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='eventparticipants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.FilePathField(blank=True, default='no photo', path='events_api/media/event_photos'),
            preserve_default=False,
        ),
    ]
