# Generated by Django 4.1.1 on 2022-10-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0004_alter_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
