# Generated by Django 4.1.1 on 2022-10-10 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_api', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
