# Generated by Django 4.1.1 on 2022-10-10 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_api', '0007_event_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='eventfavourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
