# Generated by Django 4.1.1 on 2022-10-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0008_alter_event_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events_api/media/event_photos'),
        ),
    ]
